server:
  port: 8888
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}